apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-sync
  labels:
    app: s3-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-sync
  template:
    metadata:
      labels:
        app: s3-sync
    spec:
      containers:
      - name: sync
        image: quay.io/shovanmaity/s3-sync:latest
        command:
        - run.sh
        args:
        - -i minioadmin
        - -s minioadmin
        - -u http://192.168.0.190:9000
        - -r us-east-1
        - -b b-001
        - -k /
        - -p tmp
