name: build and push image
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/shovanmaity/s3-connect:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
